DROP TABLE IMAGES;
CREATE TABLE IMAGES (S_NO int NOT NULL AUTO_INCREMENT, IMG varchar(60), PRIMARY KEY (S_NO)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_0900_ai_ci;
DROP TABLE QUESTIONS;
CREATE TABLE QUESTIONS (Q_NO int NOT NULL, Question varchar(1000) NOT NULL, OPTION1 varchar(500) NOT NULL, OPTION2 varchar(500) NOT NULL, OPTION3 varchar(500) NOT NULL, OPTION4 varchar(500) NOT NULL, ANSWER varchar(500) NOT NULL, USER_ADMIN varchar(20) NOT NULL, INDEX USER_ADMIN (USER_ADMIN)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_0900_ai_ci;
DROP TABLE StudentDetails;
CREATE TABLE StudentDetails (STUDENT_NAME varchar(30), DOB varchar(15), ZS_ID varchar(15) NOT NULL, SCHOOL_NAME varchar(20), REGISTERED_TIME date, PRIMARY KEY (ZS_ID)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_0900_ai_ci;
ALTER TABLE `QUESTIONS` ADD FOREIGN KEY (`USER_ADMIN`) REFERENCES `StudentDetails` (`ZS_ID`);
